services:
  portainer_agent:
    image: portainer/agent@sha256:86eb412391a886acf85770e586c0ef1487fad15c2d24c2b429865e8fb85c1194 # portainer/agent:2.18.4
    container_name: portainer_agent
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
